name: CI smoke test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "GitHub Actions работает ✅"
